config_t = {  
'ad_clock_frequency_hz': 0.0 ,  
'chirp_amplitude_dbm': 0.0 ,  
'chirp_bandwidth_hz': 0.0 ,  
'chirp_center_frequency_hz': 0.0 ,  
'chirp_width_ns': 0    ,  
'decimation': 0     ,  
'decimation_mode': 0     ,  
'decimation_setting': 0     ,  
'file_roll_interval_ns': 0    ,  
'frame_delay_ns': 0    ,  
'n_gates': 0     ,  
'n_gates_override': 0     ,  
'n_gates_use_override': 0,  
'pedestal_height_m': 0.0 ,  
'prp_ns': 0    ,  
'range_resolution_m': 0.0 ,  
'range_to_corner_reflector_m': 0.0 ,  
'server_state': 0     ,  
'switch_mode': 0       
}
private_config_t = {  
'pedestal_device_file_path': bytearray(128),  
'rcb_host': bytearray(128),  
'rcb_port': 0  ,  
'rcb_scope_data_device_file_path': bytearray(128),  
'gps_device_file_path' : bytearray(128),  
'scat_id': 0,  
'always_master': 0 ,  
'peer_system_enabled': 0 ,  
'peer_system_host': bytearray(128),  
'antenna_beam_width': 0.0 ,  
'corner_reflector_sigma': 0.0 ,  
'heater_control_mode': 0 ,  
'heater_control_set_point': 0.0 ,  
'heater_control_lcd_panel_set_point': 0.0 ,  
'heater_control_hysteresis': 0.0 ,  
'heater_control_proportional_gain': 0.0 ,  
'heater_control_integral_gain': 0.0 ,  
'heater_control_minimum_pulse_width_ns': 0    ,  
'heater_control_pulse_period_multiplier': 0 ,  
'cooler_set_point': 0.0 ,  
'cooler_hysteresis': 0.0 ,  
'pedestal_max_speed': 0.0 ,  
'pedestal_azimuth_offset': 0.0 ,  
'pedestal_elevation_offset': 0.0 ,  
'range_to_antenna_m': 0.0 ,  
'range_to_antenna_offset_m': 0.0 ,  
'ad_trig_delay_ns': 0    ,  
'synthesizer_trig_delay_ns': 0    ,  
'along_track_tilt_offset': 0.0 ,  
'cross_track_tilt_offset': 0.0 ,  
'calculate_ground_indices': 0 ,  
'peak_detector_copol_threshold_db': 0.0 ,  
'peak_detector_crosspol_threshold_db': 0.0 ,  
'peak_detector_range_window_width_m': 0.0 ,  
}

calibration_t = {  
'timestamp_seconds': 0     ,  
'corner_reflector_vv_power_dbm': 0.0 ,  
'corner_reflector_hh_power_dbm': 0.0 ,  
'cal_peak_dbm': 0.0 ,  
'corner_reflector_range_m': 0.0 ,  
'corner_reflector_az': 0.0 ,  
'corner_reflector_el': 0.0 ,  
'chirp_amplitude_dbm': 0.0 ,  
'chirp_bandwidth_hz': 0.0 ,  
'chirp_center_frequency_hz': 0.0 ,  
'chirp_width_ns': 0    ,  
'decimation': 0     ,  
'decimation_mode': 0     ,  
'n_summed_gates': 0       
}

file_header_t = {  
'file_header_size': 0       ,  
'meta_header_size': 0       ,  
'data_size': 0       ,  
'version_major': 0       ,  
'version_minor': 0       ,  
'version_patch': 0       ,  
'config': config_t,  
'private_config': private_config_t,  
'calibration': calibration_t  
}
